### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by devlarjay** [anthonyanader/kaliVisuals#11]
Hi. Sorry I got a super noob question. I'm tryng to run this project locally but I'm hitting a snag with firebase. I'm really new to firebase and I haven't really tried using it. Would you be kind enough to help me understand why am I having an issue like this running your app?

![image](https://user-images.githubusercontent.com/46402579/52522497-17232400-2cc1-11e9-9269-72f71c52e543.png)

I'm running this on windows BTW. Hoping that you can help me.

Thanks a lot! :)

**Comment by anthonyanader** [comment]
Hey @devlarjay :)

Thank you for taking interest in this project. The reason you are getting this error is because I have not checked the firebase base config with this file as it contains sensitive API keys and authentications.

It has nothing to do with your version of Windows.

What are you attempting to do with this project?

**Comment by devlarjay** [comment]
Hi Anthony,

Thank you so much for replying. :)

For now, I’m only trying to tinker some things that may help me build a better use case with sentiment analysis, like for instance an unofficial boxing score card using sentiment analysis or the likes.

Anyway, thank you for taking your time to answer my question. Hoping that you may check in your firebase config file soon. :)
